### ISSUE TITLE
Mismatched SHA-256 digest when downloading file

### ISSUE THREAD

**Issue by Alex-Tuch** [russelldavies/matrix-archive#34]
Hi, I'm getting an error when downloading encrypted files from rooms. When downloading files, the script shows the error "Mismatched SHA-256 digest." and files with zero size are created in the directory

**Comment by russelldavies** [comment]
This error is being generated by the matrix-nio library [here](https://github.com/poljar/matrix-nio/blob/b00c9b8632d3adfb3dfa9b0b115bf74dbd64a234/nio/crypto/attachments.py#L55). Unfortunately, I don't have the time at the moment to debug this myself so perhaps you can raise it as an issue with that library author.

**Comment by outburstx** [comment]
The solution to this problem is to change this line:

`response = await client.download(mxc.netloc, mxc.path.strip("/"))`

to

`response = await client.download(url)`

The two-argument form of client.download(server_name, media_id) is deprecated and can behave inconsistently — especially if your homeserver is federated or behind a proxy (e.g. Docker service like synapse instead of matrix.org)
